"""
Django settings for SignumNews project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
from dotenv import load_dotenv
import mimetypes
import json


mimetypes.add_type("text/css", ".css", True)

load_dotenv()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


CONFIG_PATH = os.getenv(
    "DJANGO_CONFIG_PATH", # Dont forget to add this to Apache Config or export environment variable
    BASE_DIR / "config.json"
)


with open(CONFIG_PATH) as config_file:
	config = json.load(config_file)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config["SECRET_KEY"]  # "abc"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.get("DEBUG", False)

ALLOWED_HOSTS = config.get("ALLOWED_HOSTS", [])


# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'main_app.apps.MainAppConfig',
	'user.apps.UserConfig',
	'company.apps.CompanyConfig',
	'api_public.apps.ApiPublicConfig',
	'webpack_loader',
	'rest_framework',
	'rest_framework.routers',
	'corsheaders',
	'crispy_forms',
	'crispy_bootstrap4',
	'django_ckeditor_5',
	'django_recaptcha',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	"corsheaders.middleware.CorsMiddleware",
	"django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = 'SignumNews.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'SignumNews.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': BASE_DIR / 'db.sqlite3',
	}
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

NODE_URL = BASE_DIR.joinpath('node_modules/')

ASSET_URL = BASE_DIR.joinpath('assets/') 

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.joinpath('media/')



STATICFILES_DIRS = [
	#BASE_DIR / 'static/',
	STATIC_URL,
	NODE_URL,
	ASSET_URL,
]


CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


WEBPACK_LOADER = {
	'DEFAULT': {
		'BUNDLE_DIR_NAME': 'dist/',
		
	}
}


REST_FRAMEWORK = {
	'DEFAULT_AUTHENTICATION_CLASSES': (
		'rest_framework.authentication.SessionAuthentication',
		'rest_framework.authentication.BasicAuthentication',
	),
}


CORS_ALLOW_HEADERS = [
	"accept",
	"accept-encoding",
	"authorization",
	"content-type",
	"dnt",
	"origin",
	"user-agent",
	"X-CSRFToken",
	"x-requested-with",
	"Content-Disposition",
]


LOGIN_REDIRECT_URL = 'home-page'



# Configs for ckeditor 5

CKEDITOR_5_UPLOAD_PATH = "blog_images/"

CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

CKEDITOR_5_CONFIGS = {
	"default": {
		"toolbar": [
			"heading",
			"|",
			"bold", "italic", "underline", "strikethrough",
			"|",
			"link", "blockQuote",
			"|",
			"bulletedList", "numberedList",
			"|",
			"alignment",
			"|",
			"undo", "redo",
			"|",
			"imageUpload",
			"|",
			"blockQuote",
			"|",
			"sourceEditing",
		],		
		"heading": {
			"options": [
				{"model": "paragraph", "title": "Paragraph", "class": "ck-heading_paragraph"},
				{"model": "heading1", "view": "h1", "title": "Heading 1"},
				{"model": "heading2", "view": "h2", "title": "Heading 2"},
				{"model": "heading3", "view": "h3", "title": "Heading 3"},
			]
		},
		"htmlSupport": {
			"allow": [
				{
					"name": ".*",
					"attributes": True,
					"classes": True,
					"styles": True,
				}
			]
		}
	}
}


# Google Recaptcha Config

SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']

#SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']
RECAPTCHA_PUBLIC_KEY = config['RECAPTCHA_PUBLIC_KEY']
RECAPTCHA_PRIVATE_KEY = config['RECAPTCHA_PRIVATE_KEY']
RECAPTCHA_REQUIRED_SCORE = 0.85
RECAPTCHA_ACTION = "submit"


# Logging system and configuration


BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },

        "django_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "django.log",
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
        },

        "security_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "security.log",
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 10,
            "formatter": "verbose",
        },

        "error_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "errors.log",
            "level": "ERROR",
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
        },
    },

    "loggers": {

        # Your application logs
        "": {
            "handlers": ["console", "django_file", "error_file"],
            "level": "INFO",
        },

        # Django internal warnings/errors only
        "django": {
            "handlers": ["django_file", "error_file"],
            "level": "WARNING",
            "propagate": False,
        },

        # Security events
        "django.security": {
            "handlers": ["security_file"],
            "level": "WARNING",
            "propagate": False,
        },

        # DRF errors
        "django.request": {
            "handlers": ["error_file", "console"],
            "level": "ERROR",
            "propagate": False,
        },

        # IMPORTANT: disable noisy request logging
        "django.server": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}


if not DEBUG:
	LOGGING["loggers"]["django"]["level"] = "WARNING"