# Generated by Django 5.2.12 on 2026-06-28 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAPIClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rate_limit', models.IntegerField(default=1000)),
                ('monthly_token_limit', models.IntegerField(default=100000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_key', models.CharField(max_length=250)),
                ('key', models.CharField(blank=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_public.publicapiclient')),
            ],
        ),
        migrations.CreateModel(
            name='PublicAPIKeyInternal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_key', models.CharField(max_length=250)),
                ('key_raw', models.CharField(blank=True, max_length=64, unique=True)),
                ('raw_hashed', models.CharField(blank=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_public.publicapiclient')),
            ],
        ),
        migrations.CreateModel(
            name='PublicAPIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('request_count', models.IntegerField(default=0)),
                ('api_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_public.publicapikey')),
            ],
        ),
        migrations.AddIndex(
            model_name='publicapiclient',
            index=models.Index(fields=['user', 'date_created'], name='api_public__user_id_9ee4c8_idx'),
        ),
        migrations.AddIndex(
            model_name='publicapikey',
            index=models.Index(fields=['client', 'date_created'], name='api_public__client__463b06_idx'),
        ),
        migrations.AddIndex(
            model_name='publicapikeyinternal',
            index=models.Index(fields=['client', 'date_created'], name='api_public__client__28bc08_idx'),
        ),
        migrations.AddIndex(
            model_name='publicapiusage',
            index=models.Index(fields=['api_key', 'date'], name='api_public__api_key_260504_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='publicapiusage',
            unique_together={('api_key', 'date')},
        ),
    ]
