# Generated by Django 5.2.12 on 2026-06-29 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicapiclient',
            name='total_token_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publicapiusage',
            name='date',
            field=models.DateField(db_index=True, default=datetime.datetime(2026, 6, 29, 8, 54, 12, 491122, tzinfo=datetime.timezone.utc)),
        ),
    ]
