# Generated by Django 5.2.12 on 2026-03-21 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiclient',
            name='request_count',
        ),
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('request_count', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage', to='api_public.apiclient')),
            ],
            options={
                'unique_together': {('client', 'date')},
            },
        ),
    ]
