# Generated by Django 5.2.12 on 2026-06-29 12:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_public', '0002_publicapiclient_total_token_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicapiusage',
            name='request_count_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicapiusage',
            name='tokens_used_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publicapiusage',
            name='api_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publicapiusage', to='api_public.publicapikey'),
        ),
        migrations.AlterField(
            model_name='publicapiusage',
            name='date',
            field=models.DateField(db_index=True, default=datetime.datetime(2026, 6, 29, 12, 52, 26, 170345, tzinfo=datetime.timezone.utc)),
        ),
    ]
