# Generated by Django 5.2.12 on 2026-03-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_public', '0002_remove_apiclient_request_count_apiusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='total_tokens_used',
            field=models.IntegerField(default=0),
        ),
    ]
