# Generated by Django 5.2.12 on 2026-03-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_public', '0003_apiclient_total_tokens_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiclient',
            name='total_tokens_used',
        ),
    ]
