# Generated by Django 5.2.12 on 2026-06-30 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_public', '0003_publicapiusage_request_count_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicapiusage',
            name='tokens_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publicapiusage',
            name='date',
            field=models.DateField(db_index=True, default=datetime.datetime(2026, 6, 30, 0, 20, 18, 239020, tzinfo=datetime.timezone.utc)),
        ),
    ]
