# Generated by Django 5.2.12 on 2026-06-30 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_public', '0004_publicapiusage_tokens_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicapiusage',
            name='date',
            field=models.DateField(db_index=True, default=datetime.datetime(2026, 6, 30, 9, 6, 38, 569297, tzinfo=datetime.timezone.utc)),
        ),
    ]
