# Generated by Django 5.2.12 on 2026-03-28 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_public', '0004_remove_apiclient_total_tokens_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclient',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='apiclient',
            index=models.Index(fields=['user', 'date_created'], name='api_public__user_id_a1138f_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['client', 'date_created'], name='api_public__client__069db1_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusage',
            index=models.Index(fields=['client', 'date'], name='api_public__client__3534cf_idx'),
        ),
    ]
