# Generated by Django 5.2.12 on 2026-03-30 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_public', '0005_alter_apiclient_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeyInternal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_key', models.CharField(max_length=250)),
                ('key_raw', models.CharField(blank=True, max_length=64, unique=True)),
                ('raw_hashed', models.CharField(blank=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_key_internal', to='api_public.apiclient')),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'date_created'], name='api_public__client__40dcbb_idx')],
            },
        ),
    ]
