# Generated by Django 5.2.12 on 2026-06-30 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_public', '0005_alter_publicapiusage_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publicapiusage',
            name='api_public__api_key_260504_idx',
        ),
        migrations.AlterUniqueTogether(
            name='publicapiusage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='publicapiusage',
            name='date',
            field=models.DateField(db_index=True, default=datetime.datetime(2026, 6, 30, 12, 23, 34, 239523, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='publicapiusage',
            name='api_key',
        ),
    ]
