# Generated by Django 5.2.12 on 2026-06-30 12:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_public', '0006_remove_publicapiusage_api_public__api_key_260504_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicapiusage',
            name='request_count_total',
        ),
        migrations.RemoveField(
            model_name='publicapiusage',
            name='tokens_limit',
        ),
        migrations.RemoveField(
            model_name='publicapiusage',
            name='tokens_used_total',
        ),
        migrations.AddField(
            model_name='publicapikey',
            name='tokens_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicapiusage',
            name='public_api_key',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='api_public.publicapikey'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicapiusage',
            name='date',
            field=models.DateField(db_index=True, default=datetime.datetime(2026, 6, 30, 12, 35, 14, 642769, tzinfo=datetime.timezone.utc)),
        ),
    ]
