# Generated by Django 5.2.12 on 2026-06-30 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_public', '0007_remove_publicapiusage_request_count_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicapiusage',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
