# Generated by Django 5.1.4 on 2026-01-22 23:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('publish', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'publish'], name='main_app_ca_name_5c7011_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('viaplatform', models.CharField(blank=True, db_index=True, default=None, max_length=300, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'viaplatform'], name='main_app_ne_name_934b02_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('language', models.CharField(choices=[('German', 'German'), ('English', 'English'), ('Other', 'Other')], default='German', max_length=300)),
                ('tag1', models.CharField(blank=True, db_index=True, max_length=300)),
                ('tag2', models.CharField(blank=True, db_index=True, max_length=300)),
                ('tag3', models.CharField(blank=True, db_index=True, max_length=300)),
                ('snippet', models.TextField(blank=True, max_length=320)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish', models.BooleanField(db_index=True, default=True)),
                ('algo_rating', models.FloatField(default=0.0)),
                ('category_primary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category1', to='main_app.category')),
                ('category_secondary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category2', to='main_app.category')),
                ('source', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.newssource')),
            ],
        ),
        migrations.CreateModel(
            name='UserClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('newsarticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userclick', to='main_app.newsarticle')),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userrating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('newsarticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrating', to='main_app.newsarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSourceFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersourcefollowsource', to='main_app.newssource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('newsarticle_bookmarked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.newsarticle')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'newsarticle_bookmarked'], name='main_app_bo_user_id_565a4d_idx')],
                'unique_together': {('user', 'newsarticle_bookmarked')},
            },
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['source', 'category_primary', 'category_secondary', 'tag1', 'tag2', 'tag3'], name='main_app_ne_source__d03d52_idx'),
        ),
        migrations.AddIndex(
            model_name='userclick',
            index=models.Index(fields=['newsarticle'], name='main_app_us_newsart_eaf9e8_idx'),
        ),
        migrations.AddIndex(
            model_name='userrating',
            index=models.Index(fields=['user', 'newsarticle'], name='main_app_us_user_id_52b454_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('user', 'newsarticle')},
        ),
        migrations.AddIndex(
            model_name='usersourcefollow',
            index=models.Index(fields=['user', 'source'], name='main_app_us_user_id_c4601f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersourcefollow',
            unique_together={('user', 'source')},
        ),
    ]
