# Generated by Django 5.2.12 on 2026-03-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='newssource',
            name='main_app_ne_name_934b02_idx',
        ),
        migrations.AddField(
            model_name='newssource',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='newssource',
            index=models.Index(fields=['name', 'viaplatform', 'average_rating'], name='main_app_ne_name_20f8ae_idx'),
        ),
    ]
