# Generated by Django 5.2.12 on 2026-03-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_newssource_main_app_ne_name_934b02_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='article_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newssource',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newssource',
            name='rating_sum',
            field=models.IntegerField(default=0),
        ),
    ]
