# Generated by Django 5.2.12 on 2026-03-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_newssource_article_count_newssource_rating_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='rating_sum',
            field=models.IntegerField(default=0),
        ),
    ]
