# Generated by Django 5.2.12 on 2026-03-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_newsarticle_average_rating_newsarticle_rating_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='clicks_count',
            field=models.IntegerField(default=0),
        ),
    ]
