# Generated by Django 5.2.12 on 2026-03-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_newsarticle_clicks_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarknews',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='usersourcefollow',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveIndex(
            model_name='newsarticle',
            name='main_app_ne_source__d03d52_idx',
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['source', 'category_primary', 'category_secondary', 'tag1', 'tag2', 'tag3', '-date_posted', '-clicks_count', '-average_rating'], name='main_app_ne_source__1fd905_idx'),
        ),
    ]
