# Generated by Django 5.2.12 on 2026-03-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_bookmarknews_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='average_algo_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
