# Generated by Django 5.2.12 on 2026-03-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_newssource_average_algo_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='algo_rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newssource',
            name='algo_rating_sum',
            field=models.FloatField(default=0.0),
        ),
    ]
