# Generated by Django 5.2.12 on 2026-03-28 15:47

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_newssource_algo_rating_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookmarknews',
            name='main_app_bo_user_id_565a4d_idx',
        ),
        migrations.RemoveIndex(
            model_name='newsarticle',
            name='main_app_ne_source__1fd905_idx',
        ),
        migrations.RemoveIndex(
            model_name='newssource',
            name='main_app_ne_name_20f8ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='userclick',
            name='main_app_us_newsart_eaf9e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='userrating',
            name='main_app_us_user_id_52b454_idx',
        ),
        migrations.AlterField(
            model_name='bookmarknews',
            name='date_created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='category',
            name='publish',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='algo_rating',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='average_rating',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='clicks_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='date_posted',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='article_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='average_algo_rating',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='average_rating',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='userrating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], db_index=True),
        ),
        migrations.AddIndex(
            model_name='bookmarknews',
            index=models.Index(fields=['user', 'newsarticle_bookmarked', 'date_created'], name='main_app_bo_user_id_4fcf74_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['source', 'category_primary', 'category_secondary', 'tag1', 'tag2', 'tag3', '-date_posted', '-clicks_count', 'publish', 'algo_rating', '-average_rating', 'clicks_count'], name='main_app_ne_source__a31739_idx'),
        ),
        migrations.AddIndex(
            model_name='newssource',
            index=models.Index(fields=['name', 'viaplatform', 'average_rating', 'article_count', 'average_algo_rating'], name='main_app_ne_name_66754c_idx'),
        ),
        migrations.AddIndex(
            model_name='userrating',
            index=models.Index(fields=['user', 'newsarticle', 'userrating'], name='main_app_us_user_id_9d745f_idx'),
        ),
    ]
