# Generated by Django 5.2.12 on 2026-04-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_bookmarkfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarknews',
            name='feeds',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='main_app.bookmarkfeed'),
        ),
    ]
