# Generated by Django 5.2.12 on 2026-04-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_bookmarknews_feeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkfeed',
            name='order_by',
            field=models.CharField(choices=[('by_date_of_upload', 'By date of Upload'), ('by_date_of_bookmark_added', 'By date when bookmark was added')], db_index=True, default='by_date_of_bookmark_added', max_length=250),
        ),
    ]
