# Generated by Django 5.2.12 on 2026-04-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_bookmarkfeed_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkfeed',
            name='date_updated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
