# Generated by Django 5.2.12 on 2026-06-28 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_bookmarkfeed_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkfeed',
            name='date_updated',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
    ]
