# Generated by Django 5.1.4 on 2026-01-30 13:32

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('snippet', models.TextField(blank=True, max_length=600)),
                ('image', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('publish_boolean', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
