# Generated by Django 5.1.4 on 2026-01-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasenotes',
            name='image',
        ),
    ]
