# Generated by Django 5.1.4 on 2026-01-22 23:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(choices=[('personal_feed', 'personal_feed'), ('all_articles', 'all_articles'), ('bookmarks', 'bookmarks'), ('user_sources', 'user_sources')], default='personal_feed', max_length=300)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('ranking', models.IntegerField(default=0)),
                ('order_by', models.CharField(blank=True, choices=[('by_date', 'by_date'), ('by_alphabet_source', 'by_alphabet_source'), ('by_alphabet_title', 'by_alphabet_title')], max_length=300, null=True)),
                ('publish_boolean', models.BooleanField(default=True)),
                ('category_included', models.TextField(blank=True, help_text='Comma-separated included categories', max_length=300, null=True)),
                ('tags_included', models.TextField(blank=True, help_text='Comma-separated included tags', max_length=300, null=True)),
                ('tags_excluded', models.TextField(blank=True, help_text='Comma-separated excluded tags', max_length=300, null=True)),
                ('source_included', models.TextField(blank=True, help_text='Comma-separated included source', max_length=300, null=True)),
                ('source_excluded', models.TextField(blank=True, help_text='Comma-separated excluded source', max_length=300, null=True)),
                ('min_clicks', models.FloatField(default=0)),
                ('min_rating', models.FloatField(default=0)),
                ('min_algo_rating', models.FloatField(default=0)),
                ('min_source_rating', models.FloatField(default=0)),
                ('max_days_published', models.IntegerField(default=365)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='media/profile_pics')),
                ('profile_description', models.TextField(blank=True, default='', max_length=250)),
                ('subscription_type', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=300)),
                ('favourite_article', models.ManyToManyField(blank=True, default=None, related_name='favourite_profile', to='main_app.newsarticle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('show_feed_all', models.BooleanField(default=True)),
                ('show_feed_mysources', models.BooleanField(default=True)),
                ('show_profile_module', models.BooleanField(default=True)),
                ('show_contact_module', models.BooleanField(default=True)),
                ('show_settings_module', models.BooleanField(default=True)),
                ('show_customize_module', models.BooleanField(default=True)),
                ('show_post_thread_module', models.BooleanField(default=True)),
                ('show_feed_customization_module', models.BooleanField(default=True)),
                ('show_search_module', models.BooleanField(default=True)),
                ('show_userstats_module', models.BooleanField(default=True)),
                ('show_analysis_module', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
