# Generated by Django 5.1.4 on 2026-01-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeed',
            name='category_included',
            field=models.JSONField(blank=True, default=list, help_text='List of category IDs'),
        ),
        migrations.AlterField(
            model_name='userfeed',
            name='source_excluded',
            field=models.JSONField(blank=True, default=list, help_text='List of excluded source IDs'),
        ),
        migrations.AlterField(
            model_name='userfeed',
            name='source_included',
            field=models.JSONField(blank=True, default=list, help_text='List of included source IDs'),
        ),
        migrations.AlterField(
            model_name='userfeed',
            name='tags_excluded',
            field=models.JSONField(blank=True, default=list, help_text='List of excluded tags'),
        ),
        migrations.AlterField(
            model_name='userfeed',
            name='tags_included',
            field=models.JSONField(blank=True, default=list, help_text='List of included tags'),
        ),
    ]
