# Generated by Django 5.1.4 on 2026-03-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userfeed_category_included_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='show_analysis_module',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='show_contact_module',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='show_customize_module',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='show_feed_all',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='show_feed_customization_module',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='show_feed_mysources',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='show_post_thread_module',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='show_profile_module',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='show_search_module',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='show_settings_module',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='show_userstats_module',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_article_tags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_article_timestamp',
            field=models.BooleanField(default=False),
        ),
    ]
