# Generated by Django 5.1.4 on 2026-03-16 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userprofile_user_alter_usersettings_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeed',
            name='ranking',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Business', 'Business'), ('API', 'API')], default='Free', max_length=300),
        ),
        migrations.AddConstraint(
            model_name='userfeed',
            constraint=models.UniqueConstraint(fields=('user', 'ranking'), name='unique_feed_ranking_per_user'),
        ),
    ]
