# Generated by Django 5.2.12 on 2026-03-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userfeed_ranking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='media/profile_pics/Default.png', upload_to='media/profile_pics'),
        ),
    ]
