# Generated by Django 5.2.12 on 2026-03-22 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userprofile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardCategories',
        ),
    ]
