# Generated by Django 5.2.12 on 2026-03-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_dashboardcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favourite_article',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_description',
        ),
    ]
