# Generated by Django 5.2.12 on 2026-03-25 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_userprofile_favourite_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='date_created',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
