# Generated by Django 5.2.12 on 2026-03-28 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_usersettings_date_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscoring',
            name='user',
        ),
        migrations.AlterField(
            model_name='userfeed',
            name='feed_type',
            field=models.CharField(choices=[('personal_feed', 'personal_feed'), ('all_articles', 'all_articles'), ('bookmarks', 'bookmarks'), ('user_sources', 'user_sources')], db_index=True, default='personal_feed', max_length=300),
        ),
        migrations.AlterField(
            model_name='userfeed',
            name='publish_boolean',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='userfeed',
            name='ranking',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='show_article_tags',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='show_article_timestamp',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='userfeed',
            index=models.Index(fields=['feed_type', 'ranking', 'publish_boolean'], name='user_userfe_feed_ty_104f25_idx'),
        ),
        migrations.AddIndex(
            model_name='usersettings',
            index=models.Index(fields=['user', 'show_article_tags', 'show_article_timestamp'], name='user_userse_user_id_7ced69_idx'),
        ),
        migrations.DeleteModel(
            name='UserScoring',
        ),
    ]
