# Generated by Django 5.2.12 on 2026-04-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_bookmarkfeed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookmarkFeed',
        ),
    ]
