# Generated by Django 5.2.12 on 2026-06-28 18:08

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_bookmarkfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeed',
            name='feed_type',
            field=models.CharField(choices=[('personal_feed', 'personal_feed'), ('all_articles', 'all_articles'), ('user_sources', 'user_sources')], db_index=True, default='personal_feed', max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default/Default.png', null=True, upload_to=user.models.user_profile_image_path),
        ),
    ]
